translate_dict = {
    'accumulated_hectares': {'en': 'Accumulated hectares', 'es': 'Hectáreas acumuladas', 'pt': 'Hectares acumulados'}, 
    'area': {'en': 'Area', 'es': 'Área', 'pt': 'Área'}, 
    'choose_option': {'en': 'Choose an option', 'es': 'Elije una opción', 'pt': 'Escolha uma opção'}, 
    'color_palette': {'en': 'Color Palette', 'es': 'Paleta de colores', 'pt': 'Paleta de Cores'}, 
    'crop': {'en': 'Crop', 'es': 'Cultivo', 'pt': 'Cultivo'}, 
    'crops': {'en': 'Crops', 'es': 'Cultivos', 'pt': 'Cultivos'}, 
    'dashboards': {'en': 'Dashboards', 'es': 'Tableros', 'pt': 'Painéis'},
    'download_csv': {'en': 'Download CSV', 'es': 'Descargar CSV', 'pt': 'Baixar CSV'}, 
    'error_message_date_picker': {'en': 'Select start and end date', 'es': 'Seleccione una fecha de inicio y fin', 'pt': 'Selecione uma data de início e término'}, 
    'exclude': {'en': 'Exclude', 'es': 'Excluir', 'pt': 'Excluir'}, 
    'farm': {'en': 'Farm', 'es': 'Establecimiento', 'pt': 'Fazenda'}, 
    'farms': {'en': 'Farms', 'es': 'Establecimientos', 'pt': 'Fazendas'}, 
    'field': {'en': 'Field', 'es': 'Lote', 'pt': 'Campo'}, 
    'fields': {'en': 'Fields', 'es': 'Lotes', 'pt': 'Campos'}, 
    'fields_without_crops': {'en': 'Fields without crops', 'es': 'Lotes sin cultivos', 'pt': 'Campos sem cultivos'}, 
    'fields_without_hybrids_or_varieties': {'en': 'Fields without hybrids/varieties', 'es': 'Lotes sin híbridos/variedades', 'pt': 'Campos sem híbridos/variedades'}, 
    'fields_without_sowing_date': {'en': 'Fields without sowing date', 'es': 'Lotes sin fecha de siembra', 'pt': 'Campos sem data de plantio'}, 
    'heatmap': {'en': 'Heatmap by Hectares', 'es': 'Heatmap por Hectáreas', 'pt': 'Heatmap por Hectares'}, 
    'hectares': {'en': 'Hectares', 'es': 'Hectáreas', 'pt': 'Hectares'}, 
    'hectares_by': {'en': 'Hectares by', 'es': 'Hectáreas por', 'pt': 'Hectares por'}, 
    'hectares_per_date': {'en': 'Hectares per seeding date', 'es': 'Hectáreas por fecha de siembra', 'pt': 'Hectares por data de semeadura'}, 
    'hybrid_varieties': {'en': 'Hybrids / Varieties', 'es': 'Híbridos / Variedades', 'pt': 'Híbridos / Variedades'}, 
    'hybrid_variety': {'en': 'Hybrid / Variety', 'es': 'Híbrido / Variedad', 'pt': 'Híbrido / Variedade'}, 
    'include': {'en': 'Include', 'es': 'Incluir', 'pt': 'Incluir'}, 
    'language': {'en': 'Language', 'es': 'Idioma', 'pt': 'Idioma'}, 
    'logout': {'en': 'Logout', 'es': 'Cerrar Sesión', 'pt': 'Sair'}, 
    'map_type_selector': {'en': 'Map type selector', 'es': 'Selector de tipo de mapa', 'pt': 'Seletor de tipo de mapa'}, 
    'metrics': {'en': 'Metrics', 'es': 'Métricas', 'pt': 'Métricas'}, 
    'only_no_date': {'en': 'Only Without Date', 'es': 'Solo Sin Fecha', 'pt': 'Somente Sem Data'}, 
    'points': {'en': 'Points', 'es': 'Puntos', 'pt': 'Pontos'}, 
    'polygons': {'en': 'Polygons', 'es': 'Polígonos', 'pt': 'Polígonos'}, 
    'point_map_by_field_according_to': {'en': 'Map by Field According to', 'es': 'Mapa de lotes según', 'pt': 'Mapa por Campo Segundo'}, 
    'requested_by': {'en': 'Requested by: ', 'es': 'Solicitado por: ', 'pt': 'Solicitado por: '}, 
    'season': {'en': 'Season', 'es': 'Campaña', 'pt': 'Temporada'}, 
    'seeding_date': {'en': 'Seeding Date', 'es': 'Fecha de siembra', 'pt': 'Data de Semeadura'}, 
    'seeding_date_by': {'en': 'Seeding Date by ', 'es': 'Fecha de siembra por ', 'pt': 'Data de Semeadura por '}, 
    'seeding_progress': {'en': 'Seeding progress', 'es': 'Avance de siembra', 'pt': 'Progresso da semeadura'}, 
    'select_all': {'en': 'Select all', 'es': 'Seleccionar todo', 'pt': 'Selecionar tudo'}, 
    'select_date_range': {'en': 'Select Date Range:', 'es': 'Seleccionar Rango de Fechas:', 'pt': 'Selecionar Intervalo de Datas:'}, 
    'select_grouping_field': {'en': 'Select a grouping field:', 'es': 'Seleccione un campo de agrupamiento:', 'pt': 'Selecione um campo de agrupamento:'}, 
    'select_warning': {'en': 'You must select a field to continue', 'es': 'Debe seleccionar un lote para continuar', 'pt': 'Você deve selecionar um campo para continuar'}, 
    'title': {'en': 'Fields and Crops Dashboard', 'es': 'Tablero de Lotes y Cultivos', 'pt': 'Painel de Campos e Cultivos'}, 
    'title_yield': {"en": "Yield Dashboard", "es": "Tablero de Rindes", "pt": "Painel de Rendimento"}, 
    'ver_mas': {'en': 'See more', 'es': 'Ver más', 'pt': 'Ver mais'},
    'workspace': {'en': 'Work Space', 'es': 'Espacio de Trabajo', 'pt': 'Espaço de Trabalho'}, 
    'adjusted_average_yield': {'en': 'Adjusted Average Yield', 'es': 'Rendimiento Medio Ajustado', 'pt': 'Rendimento Médio Ajustado'}, 
    'adjusted_average_yield_by': {'en': 'Adjusted Average Yield by', 'es': 'Rendimiento medio ajustado por', 'pt': 'Rendimento Médio Ajustado por'}, 
    'average_yield': {'en': 'Average Yield', 'es': 'Rendimiento Medio', 'pt': 'Rendimento Médio'}, 
    'point_map_by_layer_according_to': {'en': 'Point Map by Layer According to', 'es': 'Mapa de puntos por capa según', 'pt': 'Mapa de Pontos por Camada Segundo'}, 
    'select_yield_layer_warning': {'en': 'You must select a yield layer to continue', 'es': 'Debe seleccionar una capa de rindes para continuar', 'pt': 'Você deve selecionar uma camada de rendimento para continuar'}, 
    'weighted_yield': {'en': 'Weighted Yield', 'es': 'Rendimiento Ponderado', 'pt': 'Rendimento Ponderado'}, 
    'weighted_yield_by': {'en': 'Weighted Yield by', 'es': 'Rendimiento Ponderado por', 'pt': 'Rendimento Ponderado por'}, 
    'yield_layer': {'en': 'Yield Layer', 'es': 'Capa de Rinde', 'pt': 'Camada de Rendimento'}, 
    'yield_layers': {'en': 'Yield Layers', 'es': 'Capas de rindes', 'pt': 'Camadas de Rendimento'}
    }
