translate_dict = {
    "area": {"en": "Area", "es": "Área", "pt": "Área"},
    "area_field": {"en": "Area", "es": "Área", "pt": "Área"},
    "choose_option": {"en": "Choose an option", "es": "Elije una opción", "pt": "Escolha uma opção"},
    "color_palette": {"en": "Color Palette", "es": "Paleta de colores", "pt": "Paleta de Cores"},
    "crop": {"en": "Crop", "es": "Cultivo", "pt": "Cultivo"},
    "crop_field": {"en": "Crop", "es": "Cultivo", "pt": "Cultivo"},
    "crops": {"en": "Crops", "es": "Cultivos", "pt": "Cultivos"},
    "download_csv": {"en": "Download CSV", "es": "Descargar CSV", "pt": "Baixar CSV"},
    "farm": {"en": "Farm", "es": "Establecimiento", "pt": "Fazenda"},
    "farm_field": {"en": "Farm", "es": "Establecimiento", "pt": "Estabelecimento"},
    "farms": {"en": "Farms", "es": "Establecimientos", "pt": "Fazendas"},
    "field": {"en": "Field", "es": "Lote", "pt": "Campo"},
    "fields": {"en": "Fields", "es": "Lotes", "pt": "Campos"},
    "fields_without_crops": {"en": "Fields without crops", "es": "Lotes sin cultivos", "pt": "Campos sem cultivos"},
    "fields_without_hybrids_or_varieties": {"en": "Fields without hybrids/varieties", "es": "Lotes sin híbridos/variedades", "pt": "Campos sem híbridos/variedades"},
    "fields_without_sowing_date": {"en": "Fields without sowing date", "es": "Lotes sin fecha de siembra", "pt": "Campos sem data de plantio"},
    "heatmap": {"en": "Heatmap by Hectares", "es": "Heatmap por Hectáreas", "pt": "Heatmap por Hectares"},
    "hectares": {"en": "Hectares", "es": "Hectáreas", "pt": "Hectares"},
    "hectares_by": {"en": "Hectares by", "es": "Hectáreas por", "pt": "Hectares por"},
    "hybrid_varieties": {"en": "Hybrids / Varieties", "es": "Híbridos / Variedades", "pt": "Híbridos / Variedades"},
    "hybrid_variety": {"en": "Hybrid / Variety", "es": "Híbrido / Variedad", "pt": "Híbrido / Variedade"},
    "hybrid_variety_field": {"en": "Hybrid / Variety", "es": "Híbrido / Variedad", "pt": "Híbrido / Variedade"},
    "language": {"en": "Language", "es": "Idioma", "pt": "Idioma"},
    "logout": {"en": "Logout", "es": "Cerrar Sesión", "pt": "Sair"},
    "metrics": {"en": "Metrics", "es": "Métricas", "pt": "Métricas"},
    "point_map_by_field_according_to": {"en": "Point Map by Field According to", "es": "Mapa de lotes según", "pt": "Mapa de Pontos por Campo Segundo"},
    "requested_by": {"en": "Requested by: ", "es": "Solicitado por: ", "pt": "Solicitado por: "},
    "season": {"en": "Season", "es": "Campaña", "pt": "Temporada"},
    "season_field": {"en": "Season", "es": "Temporada", "pt": "Temporada"},
    "seeding_date": {"en": "Seeding Date", "es": "Fecha de siembra", "pt": "Data de Semeadura"},
    "seeding_date_by": {"en": "Seeding Date by ", "es": "Fecha de siembra por ", "pt": "Data de Semeadura por "},
    "select_all": {"en": "Select all", "es": "Seleccionar todo", "pt": "Selecionar tudo"},
    "select_grouping_field": {"en": "Select a grouping field:", "es": "Seleccione un campo de agrupamiento:", "pt": "Selecione um campo de agrupamento:"},
    "title": {"en": "Fields and Crops Dashboard", "es": "Tablero de Lotes y Cultivos", "pt": "Painel de Campos e Cultivos"},
    "workspace": {"en": "Work Space", "es": "Espacio de Trabajo", "pt": "Espaço de Trabalho"},
    "ws_field": {"en": "Work Space", "es": "Espacio de Trabajo", "pt": "Espaço de Trabalho"}, 
}
